language: node_js
cache: yarn

node_js:
  - 4
  - 6
  - 8
  - 9
  - "node"

before_script:
  - npm install -g gulp-cli
  - greenkeeper-lockfile-update

before_install: yarn global add greenkeeper-lockfile@1
after_script: greenkeeper-lockfile-upload
script: yarn run build

matrix:
  fast_finish: true

deploy:
  skip_cleanup: true
  provider: npm
  email: $DEPLOY_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
